### PR TITLE
Update component vertical's menu items to an IA option

### PR DESCRIPTION
**Pull request by marteki**
## Changes
- Updates the navigation with our most recent created IA for the component vertical.
- Tries to be consistent in labeling each component as a plural. (Exceptions: "Contact information", "Full width text", "Grid", "Left hand navigation", "Megamenu", "Pagination", "Heading hierarchy", and "Helper text")

## Thoughts
- Without collapsible subgroups, this vertical seems super long to try and parse/find/search at first view. We might be forcing people to rely on Ctrl-F while they learn the new organizational structures. (Something to watch for in testing, probably.)
- for @designlanguage, some possible things I only saw after getting this up for review:
  - I think that maybe "Megamenu" should be under the "Templates" vertical, instead of "Components > Navigation"? It feels much more like a template element to me that is decided on a site-wide basis than a multi-use building block for use within a single page.
  - And, maybe "Left hand navigation" is moved under "Layouts" (similar to sidebars or prefooters)?

## Screenshots
Screen Shot 2019-06-21 at 8 48 46 AM
Screen Shot 2019-06-21 at 8 49 42 AM
Screen Shot 2019-06-21 at 8 50 03 AM

### CODE REVIEW

**Comment by marteki** [comment]
Hold on, I forgot to add some stuff, so the build is failing. Stand by for fixes.

**Comment by marteki** [comment]
Note that @designlanguage and I noticed when talking about related stuff this morning: the URL for each page under "Components" does not include the tertiary categories. For example, the "Fieldsets" page would be `/components/fieldsets/` and not `/components/forms/fieldsets/`.

We're both cool with trying that out to start with.

Screen Shot 2019-06-21 at 10 19 48 AM

**Comment by contolini** [comment]
Nice work! Here's a link to a component page that exists: https://deploy-preview-13--test-design-system.netlify.com/design-system/components/buttons

**Comment by cfarm** [comment]
@marteki oh yeah good catch. Chris and I talked about adding that type of slug that follows the category hierarchy (so `/components/forms/fieldsets/`) in the future, but glad to hear this works ok for now. It's not worth implementing unless/until we decide on the IA structure.

**Pull request merged**
